theme = "snazzy-translucent"

[editor]
bufferline = "multiple"
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["file-type", "file-base-name", "spinner", "diagnostics"]
center = []
right = ["file-modification-indicator", "version-control", "mode", "position"]
separator = " |"
